# -----------------------------------------------------
# Configuracao da porta e contexto da aplicacao  
# -----------------------------------------------------  
server:
  port: 8080
  servlet.context-path: /placeti

# --------------------------------------------------------
# configuracao do banco de dados
# --------------------------------------------------------
spring:
  sql.init.mode: always
  datasource:
    url: jdbc:h2:mem:database;DB_CLOSE_ON_EXIT=FALSE 
    driverClassName: org.h2.Driver
    username: admin
    password: admin  

# --------------------------------------------------------
# configuracao do H2
# --------------------------------------------------------
  h2:
    console:
      enabled: true
      path: /h2-console  

# --------------------------------------------------------
# configuracoes da JPA
# --------------------------------------------------------
  jpa:
    properties:
        hibernate:
          dialect: org.hibernate.dialect.H2Dialect    
    defer-datasource-initialization: true
    hibernate.ddl-auto: none
